### ISSUE TITLE
Is there any possibility to release 1.2.1 with dependencies update?

### ISSUE THREAD

**Issue by mshonichev** [NowanIlfideme/pydantic-yaml#150]
Greetings!

Our project uses `pydantic-yaml` together with other modules, that had already bumped their dependencies to higher version and due to this we can't use `1.2.0` release due to version conflicts.

That commit perfectly fixes the issue
https://github.com/NowanIlfideme/pydantic-yaml/commit/df903563ced25e26f43aa6a2e760cd370ae49dea

However, to use it we had to configure `main` branch as a dependency, instead of relying on exact version, which is awkward.

Is there any possibility for the team to release 1.2.1 with updated dependencies?

Or, what is expected schedule for the update?

**Comment by NowanIlfideme** [comment]
Hi, thanks for writing - yes, I had intended to release earlier, actually, but apparently I forgot. Sorry about that!

Here's the new release: https://github.com/NowanIlfideme/pydantic-yaml/releases/tag/v1.2.1

Please re-open if something is broken here.

**Comment by mshonichev** [comment]
Oh, my god, you're so quick! Thank you so much!
