### ISSUE TITLE
Bad dependency on semver

### ISSUE THREAD

**Issue by gbritton** [NowanIlfideme/pydantic-yaml#19]
The dependency on `semver` is specified as:
```
       semver>=2.13.0,>=3.0.0.dev2  # 2 or 3 should both work
```
and since multiple constraints are combined with AND, this is equivalent to ">=3.0.0.dev2"
which I don't think was the intent.  Perhaps the correct constraint should be:
```
       semver>=2.13.0,!=3.0.0.dev1,<4  # 2 or 3 should both work
```

With the current requirements, the current release of pydantic-yaml is not installable with semver-2.13.0.
It's unclear exactly what the intent was, dev3 is presently the latest 3.0.0 version (still no stable version there).

**Comment by NowanIlfideme** [comment]
Right, thank you - forgot that there's no "or" operator in contraints. I think .dev1 would work too, so I'll set just `semver>=2.13.0,<4` for now.
