### ISSUE TITLE
`safe_load` is gonna be deprecated

### ISSUE THREAD

**Issue by wst24365888** [NowanIlfideme/pydantic-yaml#21]
Thank you for this awesome package, but I got a warning while running pytest:
```
PendingDeprecationWarning:
  safe_load will be removed, use

    yaml=YAML(typ='safe', pure=True)
    yaml.load(...)

  instead
    obj = cfg.yaml_loads(b)
```

my environment:
```
$ python --version
Python 3.10.4
```
```
ruamel-yaml==0.17.21
pydantic-yaml==0.6.3
```

Hope this one can be fix soon, thanks!

**Comment by NowanIlfideme** [comment]
Hi, got it - added this to my TODOs. Honestly, supporting both Ruamel and PyYaml seems to require more and more effort over time, but I think this can be fixed by just refactoring and wrapping a custom `safe_load` operator.
