### ISSUE TITLE
Support better (de)serialization for set other types

### ISSUE THREAD

**Issue by apirogov** [NowanIlfideme/pydantic-yaml#28]
I would like to serialize sets into lists (and vice versa when loaded), but currently I get:

```
mySet: !!set
  key1: null
  key2: null
```

A pydantic model will do the right thing when parsing a list into a set, and there are no native sets in JSON. There is no loss of information, because a set has no intrinsic order and no duplicates, so encoding them as a list in the dump and reading a set back from a list does no harm.

In general, would be cool to have something similar the `json_encoders` option that pydantic provides to override encoding of possibly custom types, instead of having to provide a whole custom yaml dumper.

But if even just `set`s were "fixed", I would be happy and that would be quite useful!

**Comment by NowanIlfideme** [comment]
Currently doable using `json_encoders` (Pydantic v1) or `@field_serializer` (Pydantic v2).

With `pydantic-yaml~=1.1.0` you might also be able to customize some serialization on the YAML side itself, though you'd need to json-encode it first, I guess.
