### ISSUE TITLE
Model serialisation fails if there is a custom type

### ISSUE THREAD

**Issue by pavelgein** [NowanIlfideme/pydantic-yaml#37]
Hi, 
I have YamlModel with one field having custom type (Enum in my case).
Yaml module can successfully represent this type, but pyndantic_yaml fails.
See the code below for an example

```python
import enum
import yaml

import pydantic
import pydantic_yaml


class MyEnum(str, enum.Enum):
    One = 'one'
    Two = 'two'


class Model(pydantic_yaml.YamlModel):
    e: MyEnum = pydantic.Field()


def do_print():
    model = Model(e=MyEnum.One)
    print(yaml.safe_dump(MyEnum.One))  # works fine
    print(model.yaml())  # fails


def main():
    do_print()


def test_repr():
    do_print()


def _enum_serializer(dumper: yaml.SafeDumper, item: MyEnum):
    return dumper.represent_str(item.value)


def __init():
    yaml.add_representer(MyEnum, _enum_serializer, Dumper=yaml.SafeDumper)


__init()


if __name__ == '__main__':
    main()
```

I can use pydantic_yaml.YamlStrEnum as a workaround, but for some reasons I would prefer to avoid it.

My package versions:
```
Python 3.10.9 (main, Dec 15 2022, 17:11:09) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> print(yaml.__version__)
5.4.1
>>> import pydantic_yaml
>>> print(pydantic_yaml.__version__)
0.9.0
>>> 
```

**Comment by NowanIlfideme** [comment]
Hi, yes - that's an issue with dumping that both ruamel and pyyaml have. I've been thinking how to get around this decently (the easiest solution is to json dump, load then yaml dump... 😅). YamlStrEnum is the current implementation, though you can also just subclass YamlEnum similarly to how it's implemented already. I understand that there might be a preexisting class, and I'm not quite sure how to handle that without writing a full engine to just dump pydantic models in a custom way. Sorry!

**Comment by NowanIlfideme** [comment]
Also, the specific yaml dumping behavior above is strange, I'll look into it - realistically it should be serializing it just fine. Are you sure pydantic-yaml is using the right engine? You can check in `pydantic_yaml.compat.yaml` I think.

**Comment by pavelgein** [comment]
> You can check in `pydantic_yaml.compat.yaml` I think.

If i understand you correctly, pydantic-yaml using ```ruamel.yaml```

```python
>>> import pydantic_yaml.compat.yaml_lib
>>> pydantic_yaml.compat.yaml_lib.yaml
<module 'ruamel.yaml' from '/opt/homebrew/lib/python3.10/site-packages/ruamel/yaml/__init__.py'>
```

And thanks for the clue.
In some way (I don't completely understand why) ```pyyaml``` and ```ruamel.yaml``` differ in a way they treat custom type serialisation.
In particular, in `pyyaml` funtion ```add_representer``` has only three arguments, but ``ruamel.yaml.add_representer``` has four. 
Explicitly passing representer argument to the later function does all the works.

The following code works as expected:
```python
import enum
import yaml

import pydantic
import pydantic_yaml
import ruamel.yaml


class MyEnum(str, enum.Enum):
    One = 'one'
    Two = 'two'


class Model(pydantic_yaml.YamlModel):
    e: MyEnum = pydantic.Field()


def do_print():
    model = Model(e=MyEnum.One)
    print(yaml.safe_dump(MyEnum.One))  # works fine
    print(model.yaml())  # fails


def main():
    do_print()


def test_repr():
    do_print()


def _enum_serializer(dumper: yaml.SafeDumper, item: MyEnum):
    return dumper.represent_str(item.value)


def __init():
    yaml.add_representer(MyEnum, _enum_serializer, Dumper=yaml.SafeDumper)
    # ruamel.yaml.add_representer(MyEnum, _enum_serializer, Dumper=ruamel.yaml.SafeDumper)  # does not work
    ruamel.yaml.add_representer(MyEnum, _enum_serializer, representer=ruamel.yaml.SafeRepresenter)


__init()


if __name__ == '__main__':
    main()
```

**Comment by NowanIlfideme** [comment]
Yep, that's unfortunately the case for now. I would really like to find the time to re-write `pydantic-yaml` with a custom YAML dumper that supports just Pydantic types (and the different `json_encoder` attributes). And ideally with no mixins required. ... hence the label on the issue.

To be clear, was the above enough to solve your issue for now?

**Comment by pavelgein** [comment]
> To be clear, was the above enough to solve your issue for now?
Yes, it works for me
