### ISSUE TITLE
Customize YAML dumping order

### ISSUE THREAD

**Issue by NowanIlfideme** [NowanIlfideme/pydantic-yaml#7]
It would be nice to dump YAML keys in field order, rather than alphabetic order. Perhaps this could be done via the Config class.

**Comment by sfowl** [comment]
I stumbled upon this issue today after switching from pyyaml to ruamel.yaml. Would be a much appreciated feature!

**Comment by NowanIlfideme** [comment]
I actually implemented this a week ago, but didn't have time to fully validate it locally to release it. I'm unsure whether it's best to change the default order to dump it by keys. Probably yes, will just need to set a new minor version for a breaking change.
