### ISSUE TITLE
Support for pydantic v2

### ISSUE THREAD

**Issue by yinzixie** [NowanIlfideme/pydantic-yaml#79]
Any plan or progress to support pydantic 2?

**Comment by NowanIlfideme** [comment]
Hi, if you install ~=1.0.0-alpha.1 then this support should already be available! Note that the API has changed (for the simpler). I only now noticed that v2 ships with v1 as well. I hope I'll be able to update it this weekend, but can't promise it. Please let me know how the pre-release version works for you, or if you're missing something critical to your work!

**Comment by yinzixie** [comment]
Thanks :smile: . I will have a look.
